sudo: required
services:
 - docker


before_install:
 - docker build -t tomasciudad/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true  tomasciudad/react-test npm test

after_sucess:
 - docker build -t tomasciudad/multi-client ./client
 - docker build -t tomasciudad/multi-nginx ./nginx
 - docker build -t tomasciudad/multi-server ./server
 - docker build -t tomasciudad/multi-worker ./worker

# log in to the docker CLI

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#take those image and push them to docker hub 

 - docker push tomasciudad/multi-client
 - docker push tomasciudad/multi-nginx
 - docker push tomasciudad/multi-server
 - docker push tomasciudad/multi-worker


